### ISSUE TITLE
Proposal: Use standard sh instead of bash for quality Unix shell scripts

### ISSUE THREAD

**Issue by ghost** [dotnet/home#29]
Target organizations: <kbd>aspnet</kbd>, <kbd>dotnet</kbd>

Inspired by many runtimes, build systems, package managers, and as a principle; please prefer using `#!/bin/sh` shebang instead of `#!/usr/bin/env bash` in Unix shell scripts; as `sh` is a standard POSIX command language interpreter (http://pubs.opengroup.org/onlinepubs/9699919799/utilities/sh.html) in particular Bourne shell which is the lowest common denominator, while bash is not available OOTB in many default shells shipped with Unix-like operating systems including *BSD.

For example, at the moment, `bash` is an *undesired* dependency on FreeBSD to build aspnet/dnx, dotnet/coreclr etc. The default (auxiliary) shell for FreeBSD is `tcsh`.

One good example, IMO, is node.js world where majority of shell scripts retain Bourne shell compatibility. To wit, install some npm package say npm itself: `npm install npm` in a tmp directory (directory-level installation, with `-g` switch addition, it would become system/global level) and find out the Bourne compatible shortcut script: `cat ./node_modules/.bin/npm`.

If there is an agreement on this proposal, we can add a checklist here like https://github.com/aspnet/Home/issues/695 to track the progress for all the repositories which require conversion of shell script files, which are used for build system in dist. After that, lets do not use any bash specific script in future. :)

This will take some major effort, as there are many files to convert and the fact that scripting in Bourne `sh` is bit more rawer than bash etc.

/cc: @akoeplinger, @davidfowl, @dougbu, @jaredpar, @mmitche, @nguerrera, @NTaylorMullen, @sokket

**Comment by agocke** [comment]
My thoughts:

I ran FreeBSD as my primary server operating system for a couple of years ~6 years ago, until I had to give it up due to hardware incompatibility.

The unnecessary use of Linux-isms in theoretically easily POSIX-portable utilities was incredibly frustrating, so I really empathize.

However, I've also had a number of cases where working with vanilla `sh` is pure hell. Most of the time, though, `bash` and `sh` inter-operate great and there is no reason to dive fully into `bash`.

There's also a complication that some `dotnet` projects, like Roslyn, currently don't support building on FreeBSD and doing so isn't on the roadmap, so supporting a new platform is a new goal.

So here's what makes sense to me: all scripts that can easily use `sh` instead of `bash` should change their shebang line to do so. This should be accepted as PRs, but not driven by the project maintainers themselves, as many of the projects don't promise explicit BSD support.

If we come across something which is necessary, currently done in `bash`, and hard to do in vanilla `sh` -- tough luck. No one uses or knows `tcsh` and it's just a step backwards. There are now many minimal bash-compatible shells, like dash, that are extremely lightweight and installing one of them should not be large burden. Most dotnet repos already have external dependencies and adding one for bash doesn't seem ridiculous to me.

**Comment by jasonwilliams200OK** [comment]
Thanks for your feedback @agocke.

In general, choosing `sh` over `bash` if possible is considered an improvement and as I have understood, your point is it is not a major improvement (as even on FreeBSD 10.2, although the default shell is csh, `bash` can be installed in parallel pretty easily).

Regarding building dotnet projects on FreeBSD:

* I was able to build Roslyn on FreeBSD last month: https://github.com/dotnet/roslyn/issues/2844#issuecomment-129221304. 

* CoreCLR already builds and FreeBSD bins are distributed via dnu.

* Here is a guide written yesterday (as part of https://github.com/dotnet/coreclr/issues/1633) for building CroreFX on FreeBSD 10.2: https://gist.github.com/jasonwilliams200OK/6efa7907e66275df2d24.

**Comment by josteink** [comment]
Seconding @agocke proposal. Having bash as a dependency isn't really that troublesame, as long as the shebang used managed to resolve it correctly (i.e., not `/bin/bash`).

I assume FreeBSD support is not on the road-map for most dotnet/aspnet projects, but if we can make them more FreeBSD-friendly with near zero-cost PRs, maybe some day later, when we get closer to where we want to be, bigger changes can be warranted too and policies can be reconsidered.

Rome wasn't built in a day and all that yadda yadda. :)

**Comment by Petermarcu** [comment]
I'm going to go ahead and close this issue on this repo. We should open issues where there are problematic scripts in the repo's that have them. That is where the work in each repo is tracked and where fixes can be made.
