### ISSUE TITLE
Fix up .NET Core 5 project details page

### ISSUE THREAD

**Issue by BethMassi** [dotnet/home#7]
@richlander can you verify the links on this page? They look wrong.

**Comment by martinwoodward** [comment]
As discussed with @blackdwarf. After dotnet/dotnet.github.io#5 update the NetCore5.md file to point at the new homepage for .NET Core? (Also we probably want to rename the file netcore rather than NetCore5 so will also need to rev the projects.json file...)

Those files control these pages:

http://www.dotnetfoundation.org/projects
http://www.dotnetfoundation.org/netcore5
